apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-weekly
spec:
  schedule: "30 0 * * 0" # "At 00:30 on Sunday."
  timeZone: "Etc/UTC"
  concurrencyPolicy: Forbid # No concurrent runs
  jobTemplate:
    spec:
      backoffLimit: 0 # No retries
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: cron-weekly
              image: "ghcr.io/ietf-tools/www:$APP_IMAGE_TAG"
              imagePullPolicy: Always
              volumeMounts:
                - name: iabwww-cfg
                  mountPath: /app/ietf/settings/local.py
                  subPath: local.py
              envFrom:
                - secretRef:
                    name: iabwww-secrets-env
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
                readOnlyRootFilesystem: true
                runAsUser: 1000
                runAsGroup: 1000
              command: ["python", "/app/manage.py", "update_index"]
          volumes:
            - name: iabwww-cfg
              configMap:
                name: files-cfgmap
